#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC795956FB489DCA9 (jannis@leidel.info)
#
Name     : jupyter-notebook-gist
Version  : 0.4.0
Release  : 2
URL      : https://pypi.python.org/packages/bf/dc/3296bca66627b57fd11bb6420464ebb7e027478f6bc5b889df2a30c5a94f/jupyter-notebook-gist-0.4.0.tar.gz
Source0  : https://pypi.python.org/packages/bf/dc/3296bca66627b57fd11bb6420464ebb7e027478f6bc5b889df2a30c5a94f/jupyter-notebook-gist-0.4.0.tar.gz
Source99 : https://pypi.python.org/packages/bf/dc/3296bca66627b57fd11bb6420464ebb7e027478f6bc5b889df2a30c5a94f/jupyter-notebook-gist-0.4.0.tar.gz.asc
Summary  : Create a gist from the Jupyter Notebook UI
Group    : Development/Tools
License  : MPL-2.0
Requires: jupyter-notebook-gist-python
BuildRequires : ipython
BuildRequires : jupyter
BuildRequires : notebook
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : requests
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : widgetsnbextension

%description
### jupyter-notebook-gist
[![Build Status](https://travis-ci.org/mozilla/jupyter-notebook-gist.svg?branch=master)](https://travis-ci.org/mozilla/jupyter-notebook-gist)

%package python
Summary: python components for the jupyter-notebook-gist package.
Group: Default

%description python
python components for the jupyter-notebook-gist package.


%prep
%setup -q -n jupyter-notebook-gist-0.4.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1486523823
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1486523823
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
